### ISSUE TITLE
Error parsing reference: "[..]" is not a valid repository/tag: invalid reference format Exited with code 1

### ISSUE THREAD

**Issue by MatheusParanhos** [builtinnya/circleci-2.0-beta-docker-example#1]
Hi, while running this repo I came across with this error
Error parsing reference: "docker-backend:3b84d7110a46c9f189478b1158883b1e3bda0ae4" is not a valid repository/tag: invalid reference format
Exited with code 1
On the last part, deployment on circle.yml
Thank you for the repo, it was very useful for a starter like me
Any ideas what that might be? thanks

**Comment by builtinnya** [comment]
Hi. I don't know what your exact setup is but it seems that you haven't set up `ECR_ENDPOINT` correctly and something may be wrong with your `.circleci/config.yml`.

Please refer [CircleCI Setup](https://github.com/builtinnya/circleci-2.0-beta-docker-example#circleci-setup) on README and make sure that you set up your AWS ECR, `config.yml`, and environment variables on CircleCI correctly.

**Comment by MatheusParanhos** [comment]
Hi @builtinnya, thanks for the answer. I haven't setup my ECR_ENDPOINT, where would I set it up? On the .tfvars file inside terraform folder? Hmm, thank you. I've setup my aws credentials but I can't seem to find where to setup the ECR_ENDPOINT, will take a look over the net now. Thanks again!

**Comment by builtinnya** [comment]
You should read [CircleCI Setup](https://github.com/builtinnya/circleci-2.0-beta-docker-example#circleci-setup) carefully :smile: 
You can set environment variables on **CircleCI project setting page**.
